name: "When updates are pushed or the defined schedule is triggered, scan the container and application for vulnerabilities"

on:

  push:

  schedule:
    - cron: '0 0 * * *'

jobs:

  scan-and-report-vulnerabilities:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    env:
      CONTAINER_REGISTRY: docker.io
      CONTAINER_IMAGE: gmirsky/hello-kubernetes

    steps:

      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Build image and version variables
        id: vars
        run: |
          echo "image=$CONTAINER_REGISTRY/$CONTAINER_IMAGE" >> $GITHUB_OUTPUT
          echo "version=$(cat src/app/package.json | jq -r .version)" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build --tag "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.version }}" \
            --build-arg IMAGE_VERSION="${{ steps.vars.outputs.version }}" \
            --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" \
            --file src/app/Dockerfile src/app

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.version }}
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4.37.0
        with:
          sarif_file: trivy-results.sarif
